### ISSUE TITLE
技术框架选型实践的一些个人见解

### ISSUE THREAD

**Issue by wataru-c** [FledgeXu/Mashiro#1]
仅供参考：

1. 代替 SASS: 个人觉得 [styled-components](https://styled-components.com/) 是 React.js 下体验最好的 CSS 开发方案，因其只需掌握 JS 和 CSS 知识而不需要额外掌握一门单独的语言语法
2. 在 2 基础上使用 [Rebass](https://rebassjs.org/) 作为样式库，Rebass 很好地与 react JSX 组件式编程结合在一起，替代 bulma 以避免大量的 className 声明、

   此外，当网站需要整体样式换肤时，只需[设置一下 JS 对象值](https://rebassjs.org/theming)即可，无需繁琐的 bulma css 样式编译

3. [代替 react-router](https://nextjs.org/docs/migrating/from-react-router): 如果随着开发而使 react-router 路由树变得复杂而难以理解维护，可以考虑换成 [Next.js](https://nextjs.org/) 框架，后者是类 php 那样 `文件路径 - 页面` 的文件结构组织方式，有助于维护（其还很容易支持 SSR 为 SEO 优化）
4. 当你开发遇到了大量的属性或状态需跨层级共享，可以试试除 Redux 外的 fb 另一新品 [Recoil](https://recoiljs.org/)

**Comment by FledgeXu** [comment]
这些工具很好，但是这个东西就4个页面，虽然我装Redux，但是都没用上😂

**Comment by FledgeXu** [comment]
anyway， 感谢你的建议。之后看情况，如果有需求重写的时候我会试试看的。
